/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mit.edu.deshan.input.ui;

import java.awt.Color;
import java.util.Calendar;
import java.util.Timer;
import javax.swing.Action;
import mit.edu.deshan.job.RandomDataEntryNewJob;
import mit.edu.deshan.util.CommonUtil;

public class MeterReading extends javax.swing.JInternalFrame {

    private RandomDataEntryNewJob dataEntry = null;

    public MeterReading() {
        this.setName("MeterReading");
        this.setTitle("Electricity Meter Reading");
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabelMeterReading = new javax.swing.JLabel();
        jTextFieldMeterReading = new javax.swing.JTextField();
        jButtonStartReading = new javax.swing.JButton();
        jLabelMessageView = new javax.swing.JLabel();
        jTextFieldConsumerId = new javax.swing.JTextField();
        jLabelstartedAt = new javax.swing.JLabel();
        jLabelNoOfReadingsTaken = new javax.swing.JLabel();
        jLabelLastReadingTakenAt = new javax.swing.JLabel();
        jLabeConsumerId = new javax.swing.JLabel();
        jButtonStopSimulation = new javax.swing.JButton();

        jLabelMeterReading.setText("Meter Reading:-");

        jTextFieldMeterReading.setText("10005");
        jTextFieldMeterReading.setToolTipText("Meter Reading");
        jTextFieldMeterReading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMeterReadingActionPerformed(evt);
            }
        });

        jButtonStartReading.setText("Start Simulation");
        jButtonStartReading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartReadingActionPerformed(evt);
            }
        });

        jLabelMessageView.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelMessageView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTextFieldConsumerId.setText("Con-0001");

        jLabeConsumerId.setText("Consumer  Id:-");

        jButtonStopSimulation.setText("Stop Simulation");
        jButtonStopSimulation.setEnabled(false);
        jButtonStopSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopSimulationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelMeterReading, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabeConsumerId, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldMeterReading, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonStartReading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonStopSimulation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextFieldConsumerId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMessageView, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelstartedAt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLastReadingTakenAt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNoOfReadingsTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMessageView, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeConsumerId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldConsumerId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMeterReading, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMeterReading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStartReading)
                    .addComponent(jButtonStopSimulation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelstartedAt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLastReadingTakenAt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNoOfReadingsTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMeterReadingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMeterReadingActionPerformed

    }//GEN-LAST:event_jTextFieldMeterReadingActionPerformed

    private void jButtonStartReadingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartReadingActionPerformed
        clearDisplayMessage();

        String intialReading = jTextFieldMeterReading.getText();
        //check if the entered start value is valid, if not do not continue
        if (!(isNumeric(intialReading))) {
            displayErrorMessage("Please enter a valid meter reading to start!");
            jTextFieldMeterReading.setText("0");
            //stops and return to ui
            return;
        }

        //check if a consumer id is given from ui, if not st a hardcoded value
        String consumerId = jTextFieldConsumerId.getText();
        if (consumerId == null || consumerId.trim().equals("")) {
            consumerId = "Con-0001";
            jTextFieldConsumerId.setText(consumerId);
        }
        
        
        String meterReading = jTextFieldMeterReading.getText();
        if (meterReading == null || meterReading.trim().equals("")) {
            meterReading = "10005";
            jTextFieldConsumerId.setText(meterReading);
        }
        
        this.jLabelstartedAt.setText("Simulation started at: " + CommonUtil.getFormattedDateTime(Calendar.getInstance().getTime()));

        //if it comes here, its a valid reading
        int initialReading = Integer.parseInt(intialReading);

        Timer timer = new Timer(); // Instantiate Timer Object
        this.dataEntry = new RandomDataEntryNewJob(); // Instantiate SheduledTask class
        dataEntry.setConsumerId(consumerId);
        dataEntry.setReading(initialReading);
        dataEntry.setjTextFieldMeterReading(jTextFieldMeterReading);
        dataEntry.setjLabelLastReadingTakenAt(jLabelLastReadingTakenAt);
        dataEntry.setjLabelNoOfReadingsTaken(jLabelNoOfReadingsTaken);
        timer.schedule(dataEntry, 0, (1000 * 5)); // Create Repetitively task for every 5 secs     

        displaySuccessMessage("Meter Simulation Started");

        this.jButtonStartReading.setEnabled(false);
        this.jButtonStopSimulation.setEnabled(true);
    }//GEN-LAST:event_jButtonStartReadingActionPerformed

    private void jButtonStopSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopSimulationActionPerformed
        if (!(dataEntry == null)) {
            dataEntry.cancel();
            this.jButtonStartReading.setEnabled(true);
            this.jButtonStopSimulation.setEnabled(false);
            displayErrorMessage("Meter Simulation Stopped");
        }

    }//GEN-LAST:event_jButtonStopSimulationActionPerformed

    void resetFormValues() {
        clearDisplayMessage();
    }

    private void clearDisplayMessage() {
        jLabelMessageView.setText(null);
        jLabelMessageView.setOpaque(false);
    }

    private void displayErrorMessage(String message) {
        displayMessage(Color.DARK_GRAY, Color.RED, message);
    }

    private void displaySuccessMessage(String message) {
        displayMessage(Color.DARK_GRAY, Color.GREEN, message);
    }

    private void displayMessage(Color foregroundColor, Color backgroundColor, String text) {
        jLabelMessageView.setBackground(backgroundColor);
        jLabelMessageView.setForeground(foregroundColor);
        jLabelMessageView.setText(text);
        jLabelMessageView.setOpaque(true);
    }

    public boolean isNumeric(String str) {
        try {
            int d = Integer.parseInt(str);
        } catch (NumberFormatException nfe) {
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonStartReading;
    private javax.swing.JButton jButtonStopSimulation;
    private javax.swing.JLabel jLabeConsumerId;
    private javax.swing.JLabel jLabelLastReadingTakenAt;
    private javax.swing.JLabel jLabelMessageView;
    private javax.swing.JLabel jLabelMeterReading;
    private javax.swing.JLabel jLabelNoOfReadingsTaken;
    private javax.swing.JLabel jLabelstartedAt;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextFieldConsumerId;
    private javax.swing.JTextField jTextFieldMeterReading;
    // End of variables declaration//GEN-END:variables

}
